### ISSUE TITLE
CLOSED

### ISSUE THREAD

**Issue by XFizzer** [Pocketmine-PHP/Sell#1]
https://github.com/Muqsit/Sell

**Comment by JackMD** [comment]
Yea stop taking others plugins and saying you own them and developed them. If not you will surely get DMCA-ed.

**Comment by georgianYT** [comment]
Sorry but alls plugins are modified and updated

**Comment by JackMD** [comment]
You changed the authors name, you removed @Muqsit name from `plugin.yml` and even from the entire source code.This is voilation of the License. I bet you haven't even read that... Under the license you are allowed to update/modify the plugin but under no condition are you allowed to change the author name from the entire code. What's even more stupid is that you are claiming of making this plugin yourself. Which if FALSE!

**Comment by HeJuKa** [comment]
ITS Not From Muqsit!Stop talking that!It is Not From him,He have i think Paste Same Codes,but Not he Download it and write IT for his self

**Comment by JackMD** [comment]
Really?
https://github.com/Pocketmine-PHP/Sell/blob/9c2897d295709af47639a962601eb2bcc79f75e8/src/SellHand/Main.php#L121
whats this then? -.-

**Comment by HeJuKa** [comment]
CLOSED!,and Stop talking that now!

**Comment by JackMD** [comment]
Really?
https://github.com/Pocketmine-PHP/Sell/blob/9c2897d295709af47639a962601eb2bcc79f75e8/src/SellHand/Main.php#L121
Whats this? -.-

**Comment by HeJuKa** [comment]
I Block You JackMD soon...

**Comment by JackMD** [comment]
Your repo is getting DMCA-ed anyway so...

**Comment by JackMD** [comment]
https://github.com/Pocketmine-PHP/Sell/blob/9c2897d295709af47639a962601eb2bcc79f75e8/src/SellHand/Main.php#L121

**Comment by HeJuKa** [comment]
I Report You.

**Comment by JackMD** [comment]
go ahead

**Comment by drewsucksatlife** [comment]
Heard there was a party here. How is everyone? Let’s all chant DMCA together!

**Comment by JackMD** [comment]
lol yea

**Comment by drewsucksatlife** [comment]
Well, that happened. The DMCA party doesn’t stop yet!

**Comment by HeJuKa** [comment]
JackMD You Download To From BajanVolgs or Piggcrates zur crates...Shut Up tuen!Or You will blocked From github

**Comment by drewsucksatlife** [comment]
I completely understand that you were wronged. Muq is definitely a fake dev, thank goodness you were there to prove it to me. Thank you.

**Comment by JackMD** [comment]
lol @HeJuKa . at least I gave the owners the credits.. unlike you I didn't removed their name from the source code.. also if you can code please compare the plugin I wrote and the one you are talking about. I had taken permission from the owner of the plugin to use a tiny part of his code.

**Comment by HeJuKa** [comment]
Okay

**Comment by HeJuKa** [comment]
Lol
